// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIUnicredit.Models;

namespace WebAPIUnicredit.Migrations
{
    [DbContext(typeof(BookDataDBContext))]
    partial class BookDataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPIUnicredit.Models.BookInstance", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("authorName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("bookName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("genre")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("publisher")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("shortDescription")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("yearPublished")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("BookInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
